config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'lists/new'
  get 'lists/create'
  get 'lists/show'
  root 'lists#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists, only: %i[index new create show] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :list_id, uniqueness: { scope: :movie_id }
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  validates :title, presence: true
  validates :overview, presence: true, uniqueness: { scope: :title }

  has_many :bookmarks
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]

  def index
    @lists = List.all
  end

  def show
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to lists_url, notice: 'List was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container p-3">
  <h1>Add a movie to a List 💜</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head >
    <title>Dani's Watch Parties</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<nav class="bg-gradient">
  <div class="container d-flex justify-content-between p-2">
    <%= link_to "🍿 Home", lists_path, class: "btn text-white" %>
  </div>
</nav>
<div class="container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url('https://images.unsplash.com/photo-1595769816263-9b910be24d5f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8bW92aWV8fHx8fHwxNjkyMzY0MzE5&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080')"></div>
    <h1>🍿 Movie Lists</h1>
    <p class='lead'>· Categorize your movie moods ·</p>
    <%= link_to "Create new list", lists_new_path, class: 'btn btn-light mt-3' %>
  </div>
  <div class="container">
    <div class="row gap-2">
      <% @lists.each do |list| %>
        <div class="card col-4" style="width: 20rem;">
          <div class="card-body ">
          <% if list.photo.attached? %>
            <%= cl_image_tag list.photo.key, class:"card-img-top", crop: :fill %>
          <% else %>
            <img src='https://source.unsplash.com/random/?movie/200x200' class="card-img-top" alt="...">
          <% end %>
            <div class="d-flex justify-content-between p-2">
              <h4 class="card-title"><%= link_to list.name, list_path(list), class: "btn text-white"%></h4>
              <i class="fa-solid fa-film p-2"></i>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container p-4">
  <div class="row justify-content-center">
    <h1>New List 📝</h1>
    <%= simple_form_for @list do |f| %>
      <div class="form-inputs form-control">
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, 'Add', class: "btn btn-default btn-info" %>
        <%= link_to "🍿 Back to lists", lists_path, class: "btn text-white" %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url('https://source.unsplash.com/random/?movie')">
    <nav class="bg-gradient">
      <div class="container d-flex justify-content-between p-2">
        <%= link_to "🍿 Category List", lists_path, class: "btn text-white" %>
        <%= link_to "Add a movie 📽️", new_list_bookmark_path(@list), class: "btn text-white" %>
      </div>
    </nav>
    <h1 class="d-flex justify-content-center p-4"><%= @list.name %></h1>
  </div>
  <div class="container">
    <div class="row gap-2 my-2">
      <% @list.bookmarks.each do |bookmark| %>
      <div class="card bg-gradient col-4" style="width: 20rem">
        <img src="<%= bookmark.movie.poster_url %>" class='card-img-top'/>
        <div class="card-body text-white">
          <div class="d-flex justify-content-between">
            <h5><strong><%= bookmark.movie.title %></strong></h5>
            <p><%=bookmark.movie.rating %>  ⭐️</p>
          </div>
          <p><em><%=bookmark.movie.overview %></em></p>
          <%= link_to "Delete", bookmark_path(bookmark), class: "btn text-danger justify-content-end",  data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{bookmark.movie.title} from your #{bookmark.list.name} list"} %>
        </div>
      </div>
      <% end %>
    </div>
  </div>